"""
Problem Description:
    - You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one 
    palindromic subsequence from s.
    - Return the minimum number of steps to make the given string empty.
    - A string is a subsequence of a given string if it is generated by deleting some characters of a given 
    string without changing its order. Note that a subsequence does not necessarily need to be contiguous.
    - A string is called palindrome if is one that reads the same backward as well as forward.

Constraints:
    - 1 <= s.length <= 1000
    - s[i] is either 'a' or 'b'.
"""

def isPalindrome(s):
    left = 0
    right = len(s) - 1

    while(left <= right):
        if s[left] != s[right]:
            return False
        left += 1
        right -= 1
    
    return True

def removePalindromeSub(s):
    """
    :type s: str
    :rtype: int
    """
    
    if isPalindrome(s) == True:
        return 1
    return 2    #one subsequence consists of all a's while other consists of all b's

s = "ababa"
print(removePalindromeSub(s)) #Output: 1

s2 = "abb"
print(removePalindromeSub(s2)) #Output: 2

s3 = "baabb"
print(removePalindromeSub(s3)) #Output: 2

s4 = "babb"
print(removePalindromeSub(s4)) #Output: 2

s5 = "baab"
print(removePalindromeSub(s5)) #Output: 1